FROM node:16 AS builder
WORKDIR /app
COPY . .
RUN npm ci
RUN npm run build
FROM node:16-alpine
WORKDIR /app
COPY --from=builder /app ./
ENV PORT=${PORT} \
    DB_TYPE=${DB_TYPE} \
    DB_HOST=${DB_HOST} \
    DB_PORT=${DB_PORT} \
    DB_USERNAME=${DB_USERNAME} \
    DB_PASSWORD=${DB_PASSWORD} \
    DB_DATABASE=${DB_DATABASE} \
    S3_ACCESS_KEY_ID=${S3_ACCESS_KEY_ID} \
    S3_SECRET_ACEESS_KEY=${S3_SECRET_ACEESS_KEY} \
    S3_BUCKET_NAME=${S3_BUCKET_NAME} \
    JWT_SECRET_KEY=${JWT_SECRET_KEY} \
    JWT_EXPIRES_IN=${JWT_EXPIRES_IN} \
    GITHUB_CLIENT_ID=${GITHUB_CLIENT_ID} \
    GITHUB_CLIENT_SECRETS=${GITHUB_CLIENT_SECRETS} \
    GITHUB_ACCESS_TOKEN=${GITHUB_ACCESS_TOKEN}
EXPOSE $PORT
CMD ["npm", "run", "start:prod"]