import * as Joi from 'joi';

export const validationSchema = Joi.object({
  NODE_ENV: Joi.string().valid('local', 'dev', 'prod').required(),
  PORT: Joi.number().required(),
  CORS_ORIGIN: Joi.string().uri().required(),
  DB_TYPE: Joi.allow('mysql').required(),
  DB_PORT: Joi.number().required(),
  DB_USERNAME: Joi.string().required(),
  DB_HOST: Joi.string().required(),
  DB_PASSWORD: Joi.string().required(),
  DB_DATABASE: Joi.string().required(),
  JWT_SECRET_KEY: Joi.string().required(),
  JWT_EXPIRES_IN: Joi.number().required(),
  JWT_REFRESH_SECRET_KEY: Joi.string().required(),
  JWT_REFRESH_EXPIRES_IN: Joi.number().required(),
  REFRESH_SALT: Joi.string().required(),
  REFRESH_ITERATIONS: Joi.number().required(),
  REFRESH_KEYLEN: Joi.number().required(),
  REFRESH_DIGEST: Joi.string().required(),
  COOKIE_SECRET_KEY: Joi.string().required(),
  COOKIE_DOMAIN: Joi.string().required(),
  AUTH_CLIENT_ID: Joi.string().required(),
  AUTH_CALLBACK: Joi.string().uri().required(),
  AUTH_CLIENT_SECRETS: Joi.string().required(),
  AUTH_ACCESS_TOKEN: Joi.string().required(),
  PERSONAL_ACCESS_TOKEN: Joi.string().required(),
  S3_ACCESS_KEY_ID: Joi.string().required(),
  S3_SECRET_ACCESS_KEY: Joi.string().required(),
  S3_BUCKET_NAME: Joi.string().required(),
  AWS_ACCESS_KEY_ID: Joi.string().required(),
  AWS_SECRET_ACCESS_KEY: Joi.string().required(),
  SSL_KEY_PATH: Joi.string().optional(),
  SSL_CERT_PATH: Joi.string().optional(),
  SSL_CA_PATH: Joi.string().optional(),
  SSL_MODE: Joi.boolean().optional(),
  SWAGGER_USER: Joi.string().optional(),
  SWAGGER_PASSWORD: Joi.string().optional(),
});
