export const USER_REPOSITORY = Symbol('USER_REPOSITORY');

export const USER_CATEGORY_REPOSITORY = Symbol('USER_CATEGORY_REPOSITORY');

export const GITHUB_OAUTH_ADAPTOR = Symbol('GITHUB_OAUTH_ADAPTOR');

export const AUTH_SERVICE_ADAPTOR = Symbol('AUTH_SERVICE_ADAPTOR');
